project:
  type: website
  
website:
  title: "Portfolio"
  navbar:
    left:
    - text: Home
      href: index.qmd
    - text: Projects
      href: projects.qmd
    - text: Resume
      href: resume.qmd
    - text: Skills
      href: skills.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kalyanjr/kalyanbandaru
      - icon: phone
        href: +1(732) 986-4815
      - icon: envelope
        href: mailto:kalyanpatrudubandaru@my.unt.edu
        
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

